<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.in_memory' shared service.

$this->services['security.user.provider.concrete.in_memory'] = $instance = new \Symfony\Component\Security\Core\User\InMemoryUserProvider();

$instance->createUser(new \Symfony\Component\Security\Core\User\User('toto', 'titi', array(0 => 'ROLE_USER')));
$instance->createUser(new \Symfony\Component\Security\Core\User\User('admin', 'admin', array(0 => 'ROLE_ADMIN')));
$instance->createUser(new \Symfony\Component\Security\Core\User\User('superadmin', 'superadmin', array(0 => 'ROLE_SUPER_ADMIN')));

return $instance;
