<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerH75xhcv\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerH75xhcv/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerH75xhcv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerH75xhcv\appDevDebugProjectContainer();
